### PR TITLE
Edgecolors

### PR DESCRIPTION
**Pull request by yonashub**
create multiple edge colors to have multiple edge colors to make following paths easy.
edges originating from a source will have same color.

### CODE REVIEW

**Comment by scottrogowski** [comment]
On first glance, I like the idea a lot! How did you choose the colors?

**Comment by yonashub** [comment]
Hi!
thanks!
I chose some of calm colors I often use.

**Comment by yonashub** [comment]
The other alternative color sets I had were the following

["#FF0000",    "#00FF00" ,    '#0000FF',   '#FF00FF',    '#800000',    '#00ffff',     "#ffc300" ]

they are easier to name and have high contrast, but they are too bright i guess.

**Comment by yonashub** [comment]
The other alternative color sets I had were the following

["#FF0000", "#00FF00" , '#0000FF', '#FF00FF', '#800000', '#00ffff', "#ffc300" ]

they are easier to name and have high contrast, but they are more bright i guess.

**Comment by scottrogowski** [comment]
I just changed the colors to be a color blind palette https://jfly.uni-koeln.de/color/#pallet and got rid of the now extra constant. Thank you again @yonashub, really good idea!

**Pull request merged**
